<a href="https://colab.research.google.com/github/Utkarsh-Marwaha/Pytorch/blob/master/2D_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

Two dimensional Tensors can essentially by thought of as matrices with some number of rows and some number of columns. One typically deals with 2D tensors while workings with gray scale image. Since a gray scale image is basically a 2D matrix of pixels with each pixel's intensity denoted by a numerical value between 0 (no intensity = black) and 255 (full intensity = white).

This being said, tensors can be extended to 3D,  4D, 5D and so on.


In [0]:
import torch

In [5]:
# create a one dimensional tensor
one_d = torch.arange(0, 9)

# print the one dimensional tensor
print(one_d)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [8]:
# reshaping the 1D tensor into a 2D tensor
two_d = one_d.view(3, 3) # 3 rows and 3 cols

# print the 2 dimensional tensor
print(two_d)

# print the number of dimensions of the tensor
print(two_d.dim())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
2


In [11]:
# accessing the first element of the 2D tensor
print(two_d[0, 0])

tensor(0)


In [12]:
# accessing element with value 5
# This element is present on the second row and the third column
print(two_d[1, 2])

tensor(5)


In [15]:
# Creating a 3D tensor
x = torch.arange(0, 18).view(2, 3, 3)
# since there are 18 elements in the tensore therefore dims have to be 
# compatible i.e. d1 * d2 * d3 = number of elements

# print the 3D tensor
print(x)

# print the number of dimensions of the tensor
print(x.dim())

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
3
