<a href="https://colab.research.google.com/github/Utkarsh-Marwaha/Pytorch/blob/master/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip3 install torch

In [0]:
import torch
from torch.nn import Linear

We start with a random value for the weight and bias and then we train our model through a gradient descent algorithm to obtain the optimal parameters to fit our data.

In [6]:
# sets a seed for generating random numbers
torch.manual_seed(1)

model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [11]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


In [12]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)


Now we will explore custom modules a robust and intuitive way of building neural networks and Pi storage.

In [0]:
import torch.nn as nn

In [0]:
class LR(nn.Module):
  
  def __init__(self, input_size, output_size):
    
    super().__init__()
    self.linear = nn.Linear(input_size , output_size)
    
  
  def forward(self, x):
    pred = self.linear(x)
    return pred 

In [20]:
torch.manual_seed(1)
model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [22]:
x = torch.tensor([[2.0], [3.3]])
print(model.forward(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)
