<a href="https://colab.research.google.com/github/Utkarsh-Marwaha/Pytorch/blob/master/Tensors_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [31]:
# create a one dimesional tensor
v = torch.tensor([1, 2, 3, 4, 5, 6])

# print the content of the tensor
print(v)

# print the data type of the tensor
print(v.dtype)


tensor([1, 2, 3, 4, 5, 6])
torch.int64


In [32]:
# accessing the 0th index of our tensor
print(v[0])

tensor(1)


In [33]:
# accessing the 1st index of our tensor
print(v[1])

tensor(2)


In [34]:
# accessing the slice from index 1 to index 4 i.e. from second element (inclusive) to fifth element (exclusive)
print(v[1:4])

tensor([2, 3, 4])


In [35]:
# create a one dimesional tensor
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])

# print the content of the float tensor
print(f)

# print the data type of the tensor
print(f.dtype)

# print the size of the tensor
print(f.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.float32
torch.Size([6])


In [36]:
# let us restructure the tensor so that it has 6 rows of data and a single column
v.view(6, 1) # very similar to the reshape method used in numpy

# Make sure that the new shape/structure of the tensor is compatible with the original one i.e. the number of elements should remain the same before and after the reshape.

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [37]:
# If we were to reshape the tensor to 3 rows and -1 cols then
v.view(3, -1)

# the value of the cols will be inferred automatically based on the length of the tensor
# The fact that the length of the tensor is 6 and the number of rows is 3, therefore the cols must be 2 for the new shape to be compatible.

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [0]:
# There will be many instances when we recieve our data in the form of numpy arrays which we have to convert to tensors
a = np.array([1, 2, 3, 4, 5])

In [39]:
# Convert the numpy array to tensor
tensor_cnv = torch.from_numpy(a)

# print the converted tensor
print(tensor_cnv)

# print the type of the tensor
print(tensor_cnv.type())

tensor([1, 2, 3, 4, 5])
torch.LongTensor


In [40]:
# Convert the tensor into a numpy array
numpy_cnv = tensor_cnv.numpy()

# print the converted numpy array
print(numpy_cnv)

# print the type of the numpy array
print(numpy_cnv.dtype)



[1 2 3 4 5]
int64
