<a href="https://colab.research.google.com/github/Utkarsh-Marwaha/Pytorch/blob/master/Matrix_Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch

In [4]:
# Creating a 2 x 3 matrix with the following elements
matrix_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)

# print the matrix
print(matrix_a)

tensor([[0, 3, 5],
        [5, 5, 2]])


In [5]:
# Creating a 3 x 2 matrix with the following elements
matrix_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)

# print the matrix
print(matrix_b)

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])


In [6]:
# conduct matrix multiplication between the two tensors
torch.matmul(matrix_a, matrix_b)

tensor([[ 29, -16],
        [ 38,   6]])

In [7]:
# The same matrix multiplication can be performed using the following: -
matrix_a @ matrix_b

tensor([[ 29, -16],
        [ 38,   6]])